name = "insight-hunter-demo"
compatibility_date = "2024-11-12"
pages_build_output_dir = "dist"
account_id = "18c8e61a3669253dcfd0c7eec6be36a3"

[vars]
APP_NAME = "Insight Hunter Demo"

[build]
upload_source_maps = true
