name = "insight-hunter-demo"
compatibility_date = "2024-11-12"
pages_build_output_dir = "dist"

[vars]
APP_NAME = "Insight Hunter Demo"
DEMO_USER = "demo"
DEMO_Pass = "demo"
SENDER_EMAIL = "no-reply@hunterturner.com"   # if you own a domain with correct SPF
NOTIFY_TO = "you@company.com"              # default recipient for demo

[[routes]]
pattern = "insight.hunterturner.com"
custom_domain = true